backend:
  name: github
  repo: jaehun-chung/jaehun-chung.github.io # ◀ 본인 깃허브 아이디로 수정!
  branch: master
media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "블로그 글"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "출시일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
