backend:
  name: github
  repo: jaehun-chung/jaehun-chung.github.io
  branch: master # 질문자님 블로그의 기본 브랜치 이름입니다.

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "blog"
    label: "블로그 글"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "제목", name: "title", widget: "string" }
      - { label: "출시일", name: "date", widget: "datetime" }
      - { label: "본문", name: "body", widget: "markdown" }
